name: Build and Deploy with Secrets

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Secret 파일 생성
      - name: Create application-secret.properties
        run: |
          echo "${{ secrets.SECRET_PROPERTIES }}" > src/main/resources/application-secret.properties

       # 3. 빌드 실행 전 gradlew 파일에 실행 권한 추가
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      # 4. 빌드 실행
      - name: Build Spring Boot Application
        run: ./gradlew clean build -x test

      # 5. Docker 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        run: |
          docker build -t dnghkm/unite-app:latest .
          docker push dnghkm/unite-app:latest

      # 7. docker-compose.yml 파일 전송
      - name: Deploy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          port: ${{ secrets.EC2_PORT }}
          key: ${{ secrets.EC2_KEY }}
          source: docker-compose.yml
          target: /home/ubuntu/app/
          debug: true

      # 8. EC2에서 docker-compose 실행
      - name: Run Docker Compose on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          port: ${{ secrets.EC2_PORT }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/app/
            docker-compose pull
            docker-compose up -d app redis
            docker image prune -af